/*
  EpiCenter — schema drift patch.
  The committed '8. Database Schema.sql' export (Oct 22 2025) predates the EF model
  in EpiCenter-backend-main. This adds the tables/columns the model expects but the
  export lacks. Generated by diffing `dotnet ef dbcontext script` against sys.columns.
  Idempotent: safe to re-run.
*/

IF OBJECT_ID('dbo.CandidateUploadResults','U') IS NULL
BEGIN
CREATE TABLE [dbo].[CandidateUploadResults] (
    [PartnerId] int NULL,
    [FullName] nvarchar(max) NULL,
    [PhoneNumber] nvarchar(max) NULL,
    [Email] nvarchar(max) NULL,
    [RoleHiredFor] nvarchar(max) NULL,
    [Diversity] nvarchar(max) NULL,
    [NoticePeriod] int NULL,
    [RelevantExperience] int NULL,
    [CurrentlyWorking] nvarchar(max) NULL,
    [CurrentOrganisation] nvarchar(max) NULL,
    [LastWorkingDay] datetime2 NULL,
    [IsDuplicate] bit NULL,
    [HiringRequestId] int NULL,
    [PrimarySkillIds] nvarchar(max) NULL,
    [SecondarySkillIds] nvarchar(max) NULL,
    [PreferredWorkLocationIds] nvarchar(max) NULL,
    [ExistingCandidateCode] nvarchar(max) NULL,
    [IsSingleEntry] bit NOT NULL,
    [CountryId] int NULL,
    [StateId] int NULL,
    [CityId] int NULL,
    [CreatedAt] datetime2 NULL
);
END
GO

IF OBJECT_ID('dbo.M_Configuration','U') IS NULL
BEGIN
CREATE TABLE [dbo].[M_Configuration] (
    [Id] int NOT NULL IDENTITY,
    [ConfigKey] nvarchar(max) NULL,
    [ConfigValue] nvarchar(max) NULL,
    [Description] nvarchar(max) NULL,
    [IsActive] bit NULL,
    [CreatedBy] int NULL,
    [CreatedAt] datetime2 NULL,
    [UpdatedBy] int NULL,
    [UpdatedAt] datetime2 NULL,
    CONSTRAINT [PK_M_Configuration] PRIMARY KEY ([Id])
);
END
GO

IF OBJECT_ID('dbo.CandidateReconsiderationHistory','U') IS NULL
BEGIN
CREATE TABLE [dbo].[CandidateReconsiderationHistory] (
    [Id] int NOT NULL IDENTITY,
    [CandidateId] int NOT NULL,
    [HiringRequestId] int NULL,
    [LastInterviewSlotId] int NULL,
    [ReconsideredByUserId] int NULL,
    [ReconsideredOn] datetime2 NULL,
    [ReconsiderReasonId] int NULL,
    [ReconsiderComments] nvarchar(max) NULL,
    [IsActive] bit NULL,
    [CreatedBy] int NULL,
    [CreatedAt] datetime2 NULL,
    [UpdatedBy] int NULL,
    [UpdatedAt] datetime2 NULL,
    CONSTRAINT [PK_CandidateReconsiderationHistory] PRIMARY KEY ([Id])
);
END
GO

IF COL_LENGTH('dbo.PartnerHRQDetails','IsProxyPartner') IS NULL ALTER TABLE [dbo].[PartnerHRQDetails] ADD [IsProxyPartner] bit NULL;
GO
IF COL_LENGTH('dbo.PartnerHRQDetails','NumberOfPositions') IS NULL ALTER TABLE [dbo].[PartnerHRQDetails] ADD [NumberOfPositions] int NULL;
GO
IF COL_LENGTH('dbo.PartnerHRQDetails','JobPriorityId') IS NULL ALTER TABLE [dbo].[PartnerHRQDetails] ADD [JobPriorityId] int NULL;
GO
IF COL_LENGTH('dbo.PartnerHRQDetails','JobPriorityName') IS NULL ALTER TABLE [dbo].[PartnerHRQDetails] ADD [JobPriorityName] nvarchar(max) NULL;
GO
IF COL_LENGTH('dbo.PartnerHRQDetails','CurrentStatusHeadCount') IS NULL ALTER TABLE [dbo].[PartnerHRQDetails] ADD [CurrentStatusHeadCount] int NULL;
GO
IF COL_LENGTH('dbo.Hiring','RMOwnerComments') IS NULL ALTER TABLE [dbo].[Hiring] ADD [RMOwnerComments] nvarchar(max) NULL;
GO
IF COL_LENGTH('dbo.Hiring','RequestApproverId') IS NULL ALTER TABLE [dbo].[Hiring] ADD [RequestApproverId] int NULL;
GO
IF COL_LENGTH('dbo.Partners','LastReinitiatedBy') IS NULL ALTER TABLE [dbo].[Partners] ADD [LastReinitiatedBy] int NULL;
GO
IF COL_LENGTH('dbo.Partners','LastReinitiatedByUserComments') IS NULL ALTER TABLE [dbo].[Partners] ADD [LastReinitiatedByUserComments] nvarchar(max) NULL;
GO
IF COL_LENGTH('dbo.InterviewSlotAllocationHistory','Duration') IS NULL ALTER TABLE [dbo].[InterviewSlotAllocationHistory] ADD [Duration] int NULL;
GO
IF COL_LENGTH('dbo.CandidateBin','AgreedForTermsConditionsOn') IS NULL ALTER TABLE [dbo].[CandidateBin] ADD [AgreedForTermsConditionsOn] datetime2 NULL;
GO
IF COL_LENGTH('dbo.CandidateBin','ManagerApprovedOn') IS NULL ALTER TABLE [dbo].[CandidateBin] ADD [ManagerApprovedOn] datetime2 NULL;
GO
IF COL_LENGTH('dbo.CandidateBin','ManagerApprovalComments') IS NULL ALTER TABLE [dbo].[CandidateBin] ADD [ManagerApprovalComments] nvarchar(max) NULL;
GO
IF COL_LENGTH('dbo.CandidateBin','ExceptionApprovalStatusId') IS NULL ALTER TABLE [dbo].[CandidateBin] ADD [ExceptionApprovalStatusId] int NULL;
GO
IF COL_LENGTH('dbo.CandidateBin','ApprovedOrDeclinedByUserId') IS NULL ALTER TABLE [dbo].[CandidateBin] ADD [ApprovedOrDeclinedByUserId] int NULL;
GO
IF COL_LENGTH('dbo.CandidateBin','AcknoledgedOn') IS NULL ALTER TABLE [dbo].[CandidateBin] ADD [AcknoledgedOn] datetime2 NULL;
GO
IF COL_LENGTH('dbo.CandidateBinHistory','ExceptionApprovalStatusId') IS NULL ALTER TABLE [dbo].[CandidateBinHistory] ADD [ExceptionApprovalStatusId] int NULL;
GO
IF COL_LENGTH('dbo.CandidateBinHistory','ManagerApprovedOn') IS NULL ALTER TABLE [dbo].[CandidateBinHistory] ADD [ManagerApprovedOn] datetime2 NULL;
GO
IF COL_LENGTH('dbo.CandidateBinHistory','ManagerApprovalComments') IS NULL ALTER TABLE [dbo].[CandidateBinHistory] ADD [ManagerApprovalComments] nvarchar(max) NULL;
GO
IF COL_LENGTH('dbo.CandidateBinHistory','ApprovedOrDeclinedByUserId') IS NULL ALTER TABLE [dbo].[CandidateBinHistory] ADD [ApprovedOrDeclinedByUserId] int NULL;
GO
IF COL_LENGTH('dbo.CandidateForms','CandidateReconsiderationHistoryId') IS NULL ALTER TABLE [dbo].[CandidateForms] ADD [CandidateReconsiderationHistoryId] int NULL;
GO
IF COL_LENGTH('dbo.CandidateForms','CandidateReintiatedOn') IS NULL ALTER TABLE [dbo].[CandidateForms] ADD [CandidateReintiatedOn] datetime2 NULL;
GO
IF COL_LENGTH('dbo.CandidateForms','CandidateDropOrReintiateByUserId') IS NULL ALTER TABLE [dbo].[CandidateForms] ADD [CandidateDropOrReintiateByUserId] int NULL;
GO
IF COL_LENGTH('dbo.CandidateForms','CandidateDropOrReintiateByUserComments') IS NULL ALTER TABLE [dbo].[CandidateForms] ADD [CandidateDropOrReintiateByUserComments] nvarchar(max) NULL;
GO
IF COL_LENGTH('dbo.CandidateFormHistory','CandidateReintiatedOn') IS NULL ALTER TABLE [dbo].[CandidateFormHistory] ADD [CandidateReintiatedOn] datetime2 NULL;
GO
IF COL_LENGTH('dbo.CandidateFormHistory','CandidateDropOrReintiateByUserId') IS NULL ALTER TABLE [dbo].[CandidateFormHistory] ADD [CandidateDropOrReintiateByUserId] int NULL;
GO
IF COL_LENGTH('dbo.CandidateFormHistory','CandidateDropOrReintiateByUserComments') IS NULL ALTER TABLE [dbo].[CandidateFormHistory] ADD [CandidateDropOrReintiateByUserComments] nvarchar(max) NULL;
GO
IF COL_LENGTH('dbo.CandidateFormHistory','CandidateReconsiderationHistoryId') IS NULL ALTER TABLE [dbo].[CandidateFormHistory] ADD [CandidateReconsiderationHistoryId] int NULL;
GO
