-- V2: Throughline application schema (as-is port of Epicenterv2), generated from the EF Core model with
--   dotnet ef dbcontext script   (apps/throughline-api, Npgsql provider, default schema 'throughline').
-- Regenerate the same way after model changes and add the diff as a new versioned migration.
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'throughline') THEN
        CREATE SCHEMA throughline;
    END IF;
END $EF$;


CREATE TABLE throughline."CandidateUploadResults" (
    "PartnerId" integer,
    "FullName" text,
    "PhoneNumber" text,
    "Email" text,
    "RoleHiredFor" text,
    "Diversity" text,
    "NoticePeriod" integer,
    "RelevantExperience" integer,
    "CurrentlyWorking" text,
    "CurrentOrganisation" text,
    "LastWorkingDay" timestamp without time zone,
    "IsDuplicate" boolean,
    "HiringRequestId" integer,
    "PrimarySkillIds" integer[],
    "SecondarySkillIds" integer[],
    "PreferredWorkLocationIds" integer[],
    "ExistingCandidateCode" text,
    "IsSingleEntry" boolean NOT NULL,
    "CountryId" integer,
    "StateId" integer,
    "CityId" integer,
    "CreatedAt" timestamp without time zone
);


CREATE TABLE throughline."EmailNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TemplateName" text,
    "NotificationId" integer,
    "ToEmail" text,
    "CCEmail" text,
    "Subject" text,
    "BodyHtml" text,
    "IsSent" boolean,
    "ExternalReference" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_EmailNotifications" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."EmailTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TemplateName" text,
    "Subject" text,
    "BodyHtml" text,
    "NotificationId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_EmailTemplates" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."Feedback" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" text,
    "Comments" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Feedback" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."M_Configuration" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ConfigKey" text,
    "ConfigValue" text,
    "Description" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_Configuration" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."M_Countries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100),
    "CountryCode" text,
    "PhoneMaxLength" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_Countries" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."M_JobLevel" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "ShortName" text,
    "DefaultExperience" integer,
    "ExperienceRange" integer,
    "StandardRate" numeric,
    "INRStandardRate" numeric,
    "ETRate" numeric,
    "INRETRate" numeric,
    "OrderId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_JobLevel" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."M_MasterData" (
    "Id" integer NOT NULL,
    "Name" text,
    "OrderId" integer,
    "MasterTypeId" integer,
    "DefaultExperience" integer,
    "ExperienceRange" integer,
    "RoundNameIds" integer[],
    "SectionId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_MasterData" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."M_SearchColumn" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Value" text,
    "GridId" integer,
    "IsPartner" boolean,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_SearchColumn" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."M_Skills" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100),
    "IsPrimary" boolean,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_Skills" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."Modules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Modules" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "Name" text,
    "CategoryType" integer,
    "Participants" text,
    "Remark" text,
    "IsRead" boolean,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."PartnerHRQDetails" (
    "HiringRequestId" integer NOT NULL,
    "HrqId" text,
    "IsProxyPartner" boolean,
    "JobTitle" text,
    "PartnerId" integer NOT NULL,
    "PartnerName" text,
    "PartnerCode" text,
    "BusinessId" integer NOT NULL,
    "BusinessName" text,
    "PartnerAssignedDate" timestamp without time zone,
    "RMOwnerId" integer,
    "RMOwnerName" text,
    "HiringStatusId" integer,
    "HiringStatusName" text,
    "NumberOfPositions" integer,
    "JobPriorityId" integer,
    "JobPriorityName" text,
    "CurrentStatusHeadCount" integer
);


CREATE TABLE throughline."QuarterDateRanges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartDay" integer NOT NULL,
    "StartMonth" integer NOT NULL,
    "EndDay" integer NOT NULL,
    "EndMonth" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_QuarterDateRanges" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."Roles" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleName" text,
    "IsActive" boolean,
    "CanOnHold" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
);


CREATE TABLE throughline."SOWPODetailHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PODetailId" integer,
    "PONumber" text,
    "StartDate" timestamp without time zone,
    "EndDate" timestamp without time zone,
    "POValue" numeric(15,2),
    "Threshold" numeric(5,2),
    "Status" boolean,
    "CRTypeId" integer,
    "CRNumber" text,
    "CRRequestDate" timestamp without time zone,
    "ExtendedDate" timestamp without time zone,
    "Comments" text,
    "SowId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_SOWPODetailHistory" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text,
    "Email" text,
    "Phone" text,
    "PasswordHash" text,
    "FirstName" text,
    "MiddleName" text,
    "LastName" text,
    "FullName" text,
    "EmployeeId" text,
    "LastLogin" timestamp without time zone,
    "ProfilePictureURL" text,
    "Bio" text,
    "NameTypeId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);


CREATE TABLE throughline."FeedbackDetail" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CriteriaId" integer NOT NULL,
    "RatingId" integer NOT NULL,
    "FeedbackId" integer NOT NULL,
    CONSTRAINT "PK_FeedbackDetail" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FeedbackDetail_Feedback_FeedbackId" FOREIGN KEY ("FeedbackId") REFERENCES throughline."Feedback" ("Id") ON DELETE CASCADE
);


CREATE TABLE throughline."M_States" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100),
    "CountryId" int,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_States" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_M_States_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id") ON DELETE RESTRICT
);


CREATE TABLE throughline."CandidateRateCard" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CandidateId" integer NOT NULL,
    "PartnerRate" numeric,
    "HourlyRate" numeric,
    "CategoryId" integer,
    "CandidateCategotyId" integer,
    "IsCustomisedRateCard" boolean,
    "DOJ" timestamp without time zone,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateRateCard" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateRateCard_M_MasterData_CandidateCategotyId" FOREIGN KEY ("CandidateCategotyId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateRateCard_M_MasterData_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES throughline."M_MasterData" ("Id")
);


CREATE TABLE throughline."CandidateReconsiderationHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CandidateId" integer NOT NULL,
    "HiringRequestId" integer,
    "LastInterviewSlotId" integer,
    "ReconsideredByUserId" integer,
    "ReconsideredOn" timestamp without time zone,
    "ReconsiderReasonId" integer,
    "ReconsiderComments" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateReconsiderationHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateReconsiderationHistory_M_MasterData_ReconsiderReas~" FOREIGN KEY ("ReconsiderReasonId") REFERENCES throughline."M_MasterData" ("Id")
);


CREATE TABLE throughline."Forms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ModuleId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Forms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Forms_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES throughline."Modules" ("Id") ON DELETE CASCADE
);


CREATE TABLE throughline."JoiningRescheduleHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FinalOnboardingDate" timestamp without time zone,
    "ModifiedOn" timestamp without time zone,
    "Modifiedby" integer,
    "Comments" text,
    "CandidateId" integer,
    "PersonalDetailsId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_JoiningRescheduleHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JoiningRescheduleHistory_Users_Modifiedby" FOREIGN KEY ("Modifiedby") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."M_Domains" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100) NOT NULL,
    "DomainManagerId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_Domains" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_M_Domains_Users_DomainManagerId" FOREIGN KEY ("DomainManagerId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."RCMSDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjectId" text,
    "JobTitle" text,
    "ProjectName" text,
    "RcMsResourceRequestId" text,
    "RequestStartDate" timestamp without time zone,
    "HiringManagerId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_RCMSDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RCMSDetails_Users_HiringManagerId" FOREIGN KEY ("HiringManagerId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."M_Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100),
    "StateId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_Cities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_M_Cities_M_States_StateId" FOREIGN KEY ("StateId") REFERENCES throughline."M_States" ("Id") ON DELETE RESTRICT
);


CREATE TABLE throughline."RoleFormAccess" (
    "RoleId" integer NOT NULL,
    "FormId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_RoleFormAccess" PRIMARY KEY ("RoleId", "FormId"),
    CONSTRAINT "FK_RoleFormAccess_Forms_FormId" FOREIGN KEY ("FormId") REFERENCES throughline."Forms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoleFormAccess_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES throughline."Roles" ("RoleId") ON DELETE CASCADE
);


CREATE TABLE throughline."Hiring" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequestorId" integer,
    "RecordTypeId" integer,
    "JobTitle" text,
    "IsRMOwnerAccepted" boolean,
    "RmOwnerAcceptedOn" timestamp without time zone,
    "RmOwnerId" integer,
    "RMOwnerComments" text,
    "EngagementTypeId" integer,
    "DomainId" integer,
    "HiringMangerId" integer,
    "HrqId" text GENERATED ALWAYS AS ('HRQ' || (("Id" - 1) / 999 + 1)::text || lpad((("Id" - 1) % 999 + 1)::text, 3, '0')) STORED NOT NULL,
    "IsParentHRQ" boolean,
    "ParentHrqId" text,
    "PreviousParentHrqId" text,
    "RCMSProjectId" text NOT NULL,
    "RCMSResourceRequestId" text NOT NULL,
    "ProjectName" text NOT NULL,
    "BusinessId" integer,
    "RequestStartDate" timestamp without time zone NOT NULL,
    "RequestCreationDate" timestamp without time zone NOT NULL,
    "HiringTypeId" integer,
    "HiringStatusId" integer,
    "PreviousHiringStatusId" integer,
    "ProjectDurationMonths" integer,
    "HrqIdURL" text GENERATED ALWAYS AS ('home/hiring-manage/hiring-details/HRQ' || (("Id" - 1) / 999 + 1)::text || lpad((("Id" - 1) % 999 + 1)::text, 3, '0')) STORED NOT NULL,
    "EmployeeId" text,
    "ReferredHrqId" text,
    "BETApproverId" integer,
    "RequestApproverId" integer,
    "ApproverUpdatedDate" timestamp without time zone,
    "ApproverComments" text,
    "ApprovalStatusId" integer,
    "ApproverEmail" text,
    "IsSinglePosition" boolean NOT NULL,
    "IsMultiplePositions" boolean NOT NULL,
    "NumberOfPositions" integer,
    "SkipScreening" boolean,
    "CancelledDate" timestamp without time zone,
    "ClosedDate" timestamp without time zone,
    "IsCandidateSelected" boolean,
    "CandidateId" integer,
    "OnholdRequestedBy" integer,
    "OnholdRaisedBy" integer,
    "OnholdRequestedDate" timestamp without time zone,
    "OnholdReasonId" integer,
    "OnholdComments" text,
    "FreezeCandidateTypes" integer[],
    "OnholdDate" timestamp without time zone,
    "OnholdReviewedByUserId" integer,
    "OnHoldReviewStatusId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Hiring" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Hiring_M_Domains_DomainId" FOREIGN KEY ("DomainId") REFERENCES throughline."M_Domains" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_ApprovalStatusId" FOREIGN KEY ("ApprovalStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_BusinessId" FOREIGN KEY ("BusinessId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_EngagementTypeId" FOREIGN KEY ("EngagementTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_HiringStatusId" FOREIGN KEY ("HiringStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_HiringTypeId" FOREIGN KEY ("HiringTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_OnHoldReviewStatusId" FOREIGN KEY ("OnHoldReviewStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_OnholdReasonId" FOREIGN KEY ("OnholdReasonId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_M_MasterData_PreviousHiringStatusId" FOREIGN KEY ("PreviousHiringStatusId") REFERENCES throughline."M_MasterData" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Hiring_M_MasterData_RecordTypeId" FOREIGN KEY ("RecordTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Hiring_Roles_OnholdRequestedBy" FOREIGN KEY ("OnholdRequestedBy") REFERENCES throughline."Roles" ("RoleId"),
    CONSTRAINT "FK_Hiring_Users_BETApproverId" FOREIGN KEY ("BETApproverId") REFERENCES throughline."Users" ("UserId"),
    CONSTRAINT "FK_Hiring_Users_HiringMangerId" FOREIGN KEY ("HiringMangerId") REFERENCES throughline."Users" ("UserId"),
    CONSTRAINT "FK_Hiring_Users_OnholdRaisedBy" FOREIGN KEY ("OnholdRaisedBy") REFERENCES throughline."Users" ("UserId"),
    CONSTRAINT "FK_Hiring_Users_OnholdReviewedByUserId" FOREIGN KEY ("OnholdReviewedByUserId") REFERENCES throughline."Users" ("UserId"),
    CONSTRAINT "FK_Hiring_Users_RequestApproverId" FOREIGN KEY ("RequestApproverId") REFERENCES throughline."Users" ("UserId"),
    CONSTRAINT "FK_Hiring_Users_RequestorId" FOREIGN KEY ("RequestorId") REFERENCES throughline."Users" ("UserId"),
    CONSTRAINT "FK_Hiring_Users_RmOwnerId" FOREIGN KEY ("RmOwnerId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."M_SubDomains" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(100),
    "DomainId" integer,
    "SubDomainManagerId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_M_SubDomains" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_M_SubDomains_M_Domains_DomainId" FOREIGN KEY ("DomainId") REFERENCES throughline."M_Domains" ("Id"),
    CONSTRAINT "FK_M_SubDomains_Users_SubDomainManagerId" FOREIGN KEY ("SubDomainManagerId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."Partners" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartnerCategoryId" integer,
    "PartnerCode" text GENERATED ALWAYS AS ('PID' || (("Id" - 1) / 999 + 1)::text || lpad((("Id" - 1) % 999 + 1)::text, 3, '0')) STORED NOT NULL,
    "PartnerName" text,
    "Nickname" text,
    "PartnerStatusId" integer,
    "StartDate" timestamp without time zone,
    "CountryId" integer,
    "StateId" integer,
    "CityId" integer,
    "Address" text,
    "Pincode" text,
    "DomainIds" integer[],
    "SubDomainIds" integer[],
    "SkillIds" integer[],
    "PartnerTireId" integer,
    "ApprovedBy" integer,
    "ApprovedStatus" boolean,
    "ApprovedDate" timestamp without time zone,
    "PartnerProfileURL" text GENERATED ALWAYS AS ('home/partner-onboarding/partner-profile/PID' || (("Id" - 1) / 999 + 1)::text || lpad((("Id" - 1) % 999 + 1)::text, 3, '0')) STORED NOT NULL,
    "IsEmailSent" boolean,
    "IsEmpaneledEnabled" boolean,
    "ServicingCountryId" integer,
    "LastActivatedDate" timestamp without time zone,
    "LastReinitiatedBy" integer,
    "LastReinitiatedByUserComments" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Partners" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Partners_M_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES throughline."M_Cities" ("Id"),
    CONSTRAINT "FK_Partners_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_Partners_M_Countries_ServicingCountryId" FOREIGN KEY ("ServicingCountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_Partners_M_MasterData_PartnerCategoryId" FOREIGN KEY ("PartnerCategoryId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Partners_M_MasterData_PartnerStatusId" FOREIGN KEY ("PartnerStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Partners_M_MasterData_PartnerTireId" FOREIGN KEY ("PartnerTireId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Partners_M_States_StateId" FOREIGN KEY ("StateId") REFERENCES throughline."M_States" ("Id"),
    CONSTRAINT "FK_Partners_Users_ApprovedBy" FOREIGN KEY ("ApprovedBy") REFERENCES throughline."Users" ("UserId") ON DELETE SET NULL,
    CONSTRAINT "FK_Partners_Users_LastReinitiatedBy" FOREIGN KEY ("LastReinitiatedBy") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."InterviewRounds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoundNumber" integer,
    "RoundNameId" integer,
    "Panel" integer[],
    "ModeOfInterview" integer,
    "Comments" text,
    "IsAddSpecificCandidates" boolean,
    "Candidates" integer[],
    "AddFeedbackCritria" boolean,
    "CategoryId" integer,
    "HiringRequestId" integer,
    "SkipScreening" boolean,
    "ScreeningCap" integer,
    "AvailableDays" text[],
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_InterviewRounds" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterviewRounds_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id"),
    CONSTRAINT "FK_InterviewRounds_M_MasterData_ModeOfInterview" FOREIGN KEY ("ModeOfInterview") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_InterviewRounds_M_MasterData_RoundNameId" FOREIGN KEY ("RoundNameId") REFERENCES throughline."M_MasterData" ("Id")
);


CREATE TABLE throughline."OnholdHiringRequest" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HiringRequestId" integer,
    "OnholdCategoryId" integer,
    "OnholdRequestedDate" timestamp without time zone,
    "OnholdRequestedByRoleId" integer,
    "OnholdRaisedByUserId" integer,
    "OnholdReasonId" integer,
    "OnholdComments" text,
    "FreezeCandidateTypes" integer[],
    "ReviewStatusId" integer,
    "OnHoldReviewedByUserId" integer,
    "ReviewedDate" timestamp without time zone,
    "ReviewedComments" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_OnholdHiringRequest" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OnholdHiringRequest_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id"),
    CONSTRAINT "FK_OnholdHiringRequest_M_MasterData_OnholdCategoryId" FOREIGN KEY ("OnholdCategoryId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_OnholdHiringRequest_M_MasterData_OnholdReasonId" FOREIGN KEY ("OnholdReasonId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_OnholdHiringRequest_M_MasterData_ReviewStatusId" FOREIGN KEY ("ReviewStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_OnholdHiringRequest_Roles_OnholdRequestedByRoleId" FOREIGN KEY ("OnholdRequestedByRoleId") REFERENCES throughline."Roles" ("RoleId"),
    CONSTRAINT "FK_OnholdHiringRequest_Users_OnHoldReviewedByUserId" FOREIGN KEY ("OnHoldReviewedByUserId") REFERENCES throughline."Users" ("UserId"),
    CONSTRAINT "FK_OnholdHiringRequest_Users_OnholdRaisedByUserId" FOREIGN KEY ("OnholdRaisedByUserId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."PartnerCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsSpecificPartner" boolean NOT NULL,
    "IsProxyPartner" boolean NOT NULL,
    "IsRecommendThePartner" boolean NOT NULL,
    "ProfileCAP" integer,
    "Comments" text NOT NULL,
    "HiringRequestId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_PartnerCategories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PartnerCategories_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id") ON DELETE CASCADE
);


CREATE TABLE throughline."JobDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "JobDescription" text,
    "HiringActivityId" integer,
    "JobPriorityId" integer,
    "HiringDate" timestamp without time zone,
    "ResourceTypeId" integer,
    "BadgeRecId" integer,
    "JobLocation" text,
    "SubDomainId" integer,
    "PrimarySkills" integer[],
    "SecondarySkills" integer[],
    "MandatoryCertificationId" integer,
    "MandatoryCertification" text,
    "JobLevelId" integer,
    "RelevantExperience" integer NOT NULL,
    "TotalExperience" integer NOT NULL,
    "CountryId" integer,
    "StateIds" integer[],
    "PrimaryCityIds" integer[],
    "SecondaryCityIds" integer[],
    "HiringRequestId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_JobDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobDetails_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id"),
    CONSTRAINT "FK_JobDetails_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_JobDetails_M_MasterData_HiringActivityId" FOREIGN KEY ("HiringActivityId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_JobDetails_M_MasterData_JobLevelId" FOREIGN KEY ("JobLevelId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_JobDetails_M_MasterData_JobPriorityId" FOREIGN KEY ("JobPriorityId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_JobDetails_M_MasterData_ResourceTypeId" FOREIGN KEY ("ResourceTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_JobDetails_M_SubDomains_SubDomainId" FOREIGN KEY ("SubDomainId") REFERENCES throughline."M_SubDomains" ("Id")
);


CREATE TABLE throughline."ContactMatrices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContactMatrixTypeId" integer,
    "Name" text,
    "Email" text,
    "ContactNumber" text,
    "CountryId" integer,
    "CountryCode" text,
    "Designation" text,
    "StatusId" integer,
    "PartnerId" integer,
    "ApprovalStatusId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_ContactMatrices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactMatrices_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_ContactMatrices_M_MasterData_ContactMatrixTypeId" FOREIGN KEY ("ContactMatrixTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_ContactMatrices_M_MasterData_StatusId" FOREIGN KEY ("StatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_ContactMatrices_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id") ON DELETE SET NULL
);


CREATE TABLE throughline."EngagementHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EngagementId" integer,
    "EngagementStatusId" integer,
    "EngagementTypeId" integer,
    "EvaluationStartDate" timestamp without time zone NOT NULL,
    "EvaluationEndDate" timestamp without time zone NOT NULL,
    "EvaluationPeriod" integer,
    "EvaluatedBy" text,
    "BusinessCenter" text,
    "BusinessId" integer,
    "IsExtendedEvaluation" boolean,
    "IsCompletedEvaluation" boolean,
    "EvaluationStatusId" integer,
    "MRUCode" text,
    "EvaluationExtendedDate" timestamp without time zone,
    "ExtendedComments" text,
    "RejectionReasonId" integer,
    "RejectionReason" text,
    "PartnerId" integer,
    "BusinessUnitId" integer,
    "RejectionReasonTypeId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_EngagementHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EngagementHistory_M_MasterData_BusinessUnitId" FOREIGN KEY ("BusinessUnitId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_EngagementHistory_M_MasterData_EngagementStatusId" FOREIGN KEY ("EngagementStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_EngagementHistory_M_MasterData_EngagementTypeId" FOREIGN KEY ("EngagementTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_EngagementHistory_M_MasterData_EvaluationStatusId" FOREIGN KEY ("EvaluationStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_EngagementHistory_M_MasterData_RejectionReasonTypeId" FOREIGN KEY ("RejectionReasonTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_EngagementHistory_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id"),
    CONSTRAINT "FK_EngagementHistory_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."Engagements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EngagementStatusId" integer,
    "EngagementTypeId" integer,
    "EvaluationStartDate" timestamp without time zone NOT NULL,
    "EvaluationEndDate" timestamp without time zone NOT NULL,
    "EvaluationPeriod" integer,
    "EvaluatedBy" text,
    "BusinessCenter" text,
    "BusinessId" integer,
    "IsExtendedEvaluation" boolean,
    "IsCompletedEvaluation" boolean,
    "EvaluationStatusId" integer,
    "MRUCode" text,
    "Comments" text,
    "EvaluationExtendedDate" timestamp without time zone,
    "ExtendedComments" text,
    "RejectionReasonId" integer,
    "RejectionReasonTypeId" integer,
    "RejectionReason" text,
    "PartnerId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Engagements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Engagements_M_MasterData_BusinessId" FOREIGN KEY ("BusinessId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Engagements_M_MasterData_EngagementStatusId" FOREIGN KEY ("EngagementStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Engagements_M_MasterData_EngagementTypeId" FOREIGN KEY ("EngagementTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Engagements_M_MasterData_EvaluationStatusId" FOREIGN KEY ("EvaluationStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Engagements_M_MasterData_RejectionReasonTypeId" FOREIGN KEY ("RejectionReasonTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_Engagements_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id") ON DELETE SET NULL
);


CREATE TABLE throughline."EscalationMatrices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContactTypeId" integer,
    "Name" text,
    "CountryId" integer,
    "ContactNumber" text,
    "Email" text,
    "Designation" text,
    "StatusId" integer,
    "PartnerId" integer,
    "ApprovalStatusId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_EscalationMatrices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EscalationMatrices_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_EscalationMatrices_M_MasterData_ContactTypeId" FOREIGN KEY ("ContactTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_EscalationMatrices_M_MasterData_StatusId" FOREIGN KEY ("StatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_EscalationMatrices_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id") ON DELETE SET NULL
);


CREATE TABLE throughline."PartnerApprovalHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartnerStatus" text,
    "Comments" text,
    "IsReinitiated" boolean,
    "PartnerId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_PartnerApprovalHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PartnerApprovalHistory_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id") ON DELETE CASCADE
);


CREATE TABLE throughline."PartnerEmpanel" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsEmpaneledPartner" boolean NOT NULL,
    "EmpanelmentStartDate" timestamp without time zone,
    "IsThisGPApproved" boolean,
    "AgreementTypeId" integer,
    "ContractId" text,
    "GPId" text,
    "SOWSigningDate" timestamp without time zone,
    "GPApprovalDate" timestamp without time zone,
    "EmpanelmentComments" text,
    "PANID" text,
    "GSTID" text,
    "TANID" text,
    "IsExtendEvaluation" boolean NOT NULL,
    "EvaluationExtendedDate" timestamp without time zone,
    "RejectionReasonId" integer,
    "RejectionReason" text,
    "PartnerId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_PartnerEmpanel" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PartnerEmpanel_M_MasterData_AgreementTypeId" FOREIGN KEY ("AgreementTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_PartnerEmpanel_M_MasterData_RejectionReasonId" FOREIGN KEY ("RejectionReasonId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_PartnerEmpanel_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id")
);


CREATE TABLE throughline."SOWDetailHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SOWID" integer,
    "SOWNumber" text,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "TCValue" numeric(15,2) NOT NULL,
    "Status" boolean,
    "CRTypeId" integer,
    "CRNumber" text,
    "CRRequestDate" timestamp without time zone,
    "ExtendedDate" timestamp without time zone,
    "Comments" text,
    "IsRateChanged" boolean,
    "PartnerId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_SOWDetailHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SOWDetailHistory_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id")
);


CREATE TABLE throughline."SOWDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SOWNumber" text,
    "StartDate" timestamp without time zone,
    "EndDate" timestamp without time zone,
    "TCValue" numeric(15,2) NOT NULL,
    "Status" boolean,
    "Comments" text,
    "PartnerId" integer,
    "ApprovalStatusId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_SOWDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SOWDetails_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id") ON DELETE SET NULL
);


CREATE TABLE throughline."UserRolesMapping" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "PartnerId" integer,
    "AssignedAt" timestamp without time zone,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_UserRolesMapping" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRolesMapping_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id"),
    CONSTRAINT "FK_UserRolesMapping_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES throughline."Roles" ("RoleId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRolesMapping_Users_UserId" FOREIGN KEY ("UserId") REFERENCES throughline."Users" ("UserId") ON DELETE CASCADE
);


CREATE TABLE throughline."FeedbackCritriaOptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CriteriaOptionId" integer,
    "Value" boolean,
    "FeedbackCategoryId" integer,
    "InterviewRoundId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_FeedbackCritriaOptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FeedbackCritriaOptions_InterviewRounds_InterviewRoundId" FOREIGN KEY ("InterviewRoundId") REFERENCES throughline."InterviewRounds" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FeedbackCritriaOptions_M_MasterData_CriteriaOptionId" FOREIGN KEY ("CriteriaOptionId") REFERENCES throughline."M_MasterData" ("Id")
);


CREATE TABLE throughline."InterviewSlotAllocationHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HiringRequestId" integer,
    "CandidateId" integer,
    "PartnerId" integer,
    "CurrentRoundId" integer,
    "Date" timestamp without time zone,
    "Time" interval,
    "Panel" integer[],
    "ValidityHours" integer,
    "Duration" integer,
    "IsPartnerAccepted" boolean,
    "RejectedReason" text,
    "RejectedOn" timestamp without time zone,
    "RejectionCount" integer,
    "IsResheduled" boolean,
    "Feedback" text,
    "CandidateInterviewStatusId" integer,
    "AddedAt" timestamp without time zone,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_InterviewSlotAllocationHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterviewSlotAllocationHistory_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id"),
    CONSTRAINT "FK_InterviewSlotAllocationHistory_InterviewRounds_CurrentRound~" FOREIGN KEY ("CurrentRoundId") REFERENCES throughline."InterviewRounds" ("Id"),
    CONSTRAINT "FK_InterviewSlotAllocationHistory_M_MasterData_CandidateInterv~" FOREIGN KEY ("CandidateInterviewStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_InterviewSlotAllocationHistory_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id")
);


CREATE TABLE throughline."HiringReqPartner" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartnerId" integer,
    "AssignedOn" timestamp without time zone,
    "PartnerCategoryId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_HiringReqPartner" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HiringReqPartner_PartnerCategories_PartnerCategoryId" FOREIGN KEY ("PartnerCategoryId") REFERENCES throughline."PartnerCategories" ("Id") ON DELETE CASCADE
);


CREATE TABLE throughline."SOWCRS" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CRTypeId" integer,
    "CRNumber" text,
    "CRValue" numeric(18,2),
    "CRRequestDate" timestamp without time zone,
    "ExtendedDate" timestamp without time zone,
    "IsRateChanged" boolean,
    "Comments" text,
    "SOWId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_SOWCRS" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SOWCRS_SOWDetails_SOWId" FOREIGN KEY ("SOWId") REFERENCES throughline."SOWDetails" ("Id")
);


CREATE TABLE throughline."SOWPODetail" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PONumber" text,
    "StartDate" timestamp without time zone,
    "EndDate" timestamp without time zone,
    "POValue" numeric(15,2),
    "Threshold" numeric(5,2),
    "Status" boolean,
    "SowId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_SOWPODetail" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SOWPODetail_SOWDetails_SowId" FOREIGN KEY ("SowId") REFERENCES throughline."SOWDetails" ("Id") ON DELETE SET NULL
);


CREATE TABLE throughline."POCRS" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CRTypeId" integer,
    "CRNumber" text,
    "CRValue" numeric(18,2),
    "CRRequestDate" timestamp without time zone,
    "ExtendedDate" timestamp without time zone,
    "IsRateChanged" boolean,
    "Comments" text,
    "POId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_POCRS" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_POCRS_SOWPODetail_POId" FOREIGN KEY ("POId") REFERENCES throughline."SOWPODetail" ("Id") ON DELETE SET NULL
);


CREATE TABLE throughline."AssetDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsJoinConfirmed" boolean,
    "IsPCAllocated" boolean,
    "PCRequestCreatedDate" timestamp without time zone,
    "PCRequestRefNo" text,
    "PCSerialNo" text,
    "PCAllocationDate" timestamp without time zone,
    "ModeOfPcShipmentId" integer,
    "PCReceivedOn" timestamp without time zone,
    "PCConfigurationDate" timestamp without time zone,
    "ITAssetStatusID" integer,
    "ComplianceFollowedId" integer,
    "DelayCategoryId" integer,
    "Comments" text,
    "CandidatePersonalDetailsId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_AssetDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssetDetails_M_MasterData_ComplianceFollowedId" FOREIGN KEY ("ComplianceFollowedId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_AssetDetails_M_MasterData_DelayCategoryId" FOREIGN KEY ("DelayCategoryId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_AssetDetails_M_MasterData_ITAssetStatusID" FOREIGN KEY ("ITAssetStatusID") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_AssetDetails_M_MasterData_ModeOfPcShipmentId" FOREIGN KEY ("ModeOfPcShipmentId") REFERENCES throughline."M_MasterData" ("Id")
);


CREATE TABLE throughline."Calibrations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HrqId" text,
    "JobTitle" text,
    "Attendees" text,
    "CalibrationDate" timestamp without time zone,
    "PrimarySkillsChanges" text,
    "SecondarySkillsChnages" text,
    "Certifications" text,
    "DocumentId" integer,
    "DocumentsId" integer,
    "Comments" text,
    "HiringRequestId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_Calibrations" PRIMARY KEY ("Id")
);


CREATE TABLE throughline."CandidateBgvDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorId" integer,
    "PGUId" integer,
    "StartDate" timestamp without time zone,
    "IsUploadedBGVDocs" boolean,
    "NDAAvailability" boolean,
    "NDAAvailabilityDocId" integer,
    "CDAAvailability" boolean,
    "CDAAvailabilityDocId" integer,
    "IsBGVAvailableWithPartner" boolean,
    "BGVStatusId" integer,
    "BGVStatusName" text,
    "BGVCategoryId" integer,
    "BGVCategoryName" text,
    "BGVCompletionDate" timestamp without time zone,
    "CandidateBGVCompleted" boolean,
    "CandidatePersonalDetailsId" integer,
    "Comments" text,
    "LastUpdated" timestamp without time zone,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateBgvDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateBgvDetails_M_MasterData_PGUId" FOREIGN KEY ("PGUId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateBgvDetails_Partners_VendorId" FOREIGN KEY ("VendorId") REFERENCES throughline."Partners" ("Id")
);


CREATE TABLE throughline."DocumentDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AttachmentName" text,
    "AttachmentURL" text,
    "PartnerId" integer,
    "UploadBGVDocId" integer,
    "AdditionalDocId" integer,
    "DocType" integer,
    "PartnerEmpanelId" integer,
    "MarkAsDeleted" boolean,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_DocumentDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentDetails_CandidateBgvDetails_AdditionalDocId" FOREIGN KEY ("AdditionalDocId") REFERENCES throughline."CandidateBgvDetails" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentDetails_CandidateBgvDetails_UploadBGVDocId" FOREIGN KEY ("UploadBGVDocId") REFERENCES throughline."CandidateBgvDetails" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentDetails_PartnerEmpanel_PartnerEmpanelId" FOREIGN KEY ("PartnerEmpanelId") REFERENCES throughline."PartnerEmpanel" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentDetails_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id") ON DELETE CASCADE
);


CREATE TABLE throughline."CandidateBin" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartnerId" integer,
    "HiringRequestId" integer,
    "IsSingleEntry" boolean NOT NULL,
    "FullName" text,
    "PhoneNumber" text,
    "Email" text,
    "CountryId" integer,
    "StateId" integer,
    "CityId" integer,
    "Diversity" text,
    "NoticePeriod" integer,
    "RelevantExperience" integer,
    "CurrentlyWorking" text,
    "CurrentOrganisation" text,
    "LastOrganisation" text,
    "LastWorkingDay" timestamp without time zone,
    "ResumeId" integer,
    "EmployeeId" text,
    "ResourceTypeId" integer,
    "PCLifecycleId" text,
    "RequestedMicrosoftAccount" boolean,
    "ConsideredForFutureRequirements" boolean,
    "IsReferred" text,
    "ReferredBy" text,
    "IntakeStatusId" integer,
    "IsAgreedForTermsConditions" boolean,
    "AgreedForTermsConditionsOn" timestamp without time zone,
    "IsRequestException" boolean,
    "ResumeUploadedOn" timestamp without time zone,
    "IsDuplicate" boolean,
    "ExistingCandidateCode" text,
    "PartnerComments" text,
    "IsManagerApproved" boolean,
    "ManagerApprovedOn" timestamp without time zone,
    "ManagerApprovalComments" text,
    "ExceptionApprovalStatusId" integer,
    "ApprovedOrDeclinedByUserId" integer,
    "AcknoledgedOn" timestamp without time zone,
    "ReUploadedCandidateOn" timestamp without time zone,
    "RoleHiredFor" text,
    "PrimarySkillIds" text,
    "SecondarySkillIds" text,
    "PreferredWorkLocationIds" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateBin" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateBin_DocumentDetails_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES throughline."DocumentDetails" ("Id"),
    CONSTRAINT "FK_CandidateBin_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id"),
    CONSTRAINT "FK_CandidateBin_M_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES throughline."M_Cities" ("Id"),
    CONSTRAINT "FK_CandidateBin_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_CandidateBin_M_MasterData_IntakeStatusId" FOREIGN KEY ("IntakeStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateBin_M_MasterData_ResourceTypeId" FOREIGN KEY ("ResourceTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateBin_M_States_StateId" FOREIGN KEY ("StateId") REFERENCES throughline."M_States" ("Id"),
    CONSTRAINT "FK_CandidateBin_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id"),
    CONSTRAINT "FK_CandidateBin_Users_ApprovedOrDeclinedByUserId" FOREIGN KEY ("ApprovedOrDeclinedByUserId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."CandidateBinHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartnerId" integer,
    "HiringRequestId" integer,
    "IsSingleEntry" boolean NOT NULL,
    "FullName" text,
    "PhoneNumber" text,
    "Email" text,
    "CountryId" integer,
    "StateId" integer,
    "CityId" integer,
    "Diversity" text,
    "NoticePeriod" integer,
    "RelevantExperience" integer,
    "CurrentlyWorking" text,
    "CurrentOrganisation" text,
    "LastOrganisation" text,
    "LastWorkingDay" timestamp without time zone,
    "ResumeId" integer,
    "EmployeeId" text,
    "ResourceTypeId" integer,
    "PCLifecycleId" text,
    "RequestedMicrosoftAccount" boolean,
    "ConsideredForFutureRequirements" boolean,
    "IsReferred" text,
    "ReferredBy" text,
    "IntakeStatusId" integer,
    "IsAgreedForTermsConditions" boolean,
    "IsRequestException" boolean,
    "ResumeUploadedOn" timestamp without time zone,
    "IsDuplicate" boolean,
    "ExistingCandidateCode" text,
    "PartnerComments" text,
    "ExceptionApprovalStatusId" integer,
    "IsManagerApproved" boolean,
    "ManagerApprovedOn" timestamp without time zone,
    "ManagerApprovalComments" text,
    "ApprovedOrDeclinedByUserId" integer,
    "RoleHiredFor" text,
    "PrimarySkillIds" text,
    "SecondarySkillIds" text,
    "PreferredWorkLocationIds" text,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateBinHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_DocumentDetails_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES throughline."DocumentDetails" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_M_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES throughline."M_Cities" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_M_MasterData_IntakeStatusId" FOREIGN KEY ("IntakeStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_M_MasterData_ResourceTypeId" FOREIGN KEY ("ResourceTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_M_States_StateId" FOREIGN KEY ("StateId") REFERENCES throughline."M_States" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id"),
    CONSTRAINT "FK_CandidateBinHistory_Users_ApprovedOrDeclinedByUserId" FOREIGN KEY ("ApprovedOrDeclinedByUserId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."CandidateForms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HiringRequestId" integer,
    "CandidateCode" text GENERATED ALWAYS AS ('CA' || (("Id" - 1) / 999 + 1)::text || lpad((("Id" - 1) % 999 + 1)::text, 3, '0')) STORED NOT NULL,
    "IsSingleEntry" boolean NOT NULL,
    "FullName" text,
    "PhoneNumber" text,
    "Email" text,
    "RoleHiredFor" text,
    "PrimarySkillIds" integer[],
    "SecondarySkillIds" integer[],
    "Diversity" text,
    "CountryId" integer,
    "StateId" integer,
    "CityId" integer,
    "PreferredWorkLocationIds" integer[],
    "NoticePeriod" integer,
    "RelevantExperience" integer,
    "CurrentlyWorking" text,
    "CurrentOrganisation" text,
    "LastOrganisation" text,
    "PartnerId" integer,
    "LastWorkingDay" timestamp without time zone,
    "ResumeId" integer,
    "ResumeUploadedOn" timestamp without time zone,
    "IsReferred" text,
    "ReferredBy" text,
    "IsAgreedForTermsConditions" boolean,
    "CandidateRateCardId" integer,
    "IntakeStatusId" integer,
    "CandidateReconsiderationHistoryId" integer,
    "ReUploadedCandidateOn" timestamp without time zone,
    "EmployeeId" text,
    "ResourceTypeId" integer,
    "PCLifecycleId" text,
    "RequestedMicrosoftAccount" boolean,
    "ConsideredForFutureRequirements" boolean,
    "JoiningConfirmationComments" text,
    "Comments" text,
    "CandidateFreezedReason" text,
    "IsFreezed" boolean,
    "PreviousIntakeStatusId" integer,
    "CandidateStatusId" integer,
    "ApprovedBy" integer,
    "ApprovedDate" timestamp without time zone,
    "IsDuplicate" boolean,
    "IsScreeningCompleted" boolean,
    "ScreeningCompletedOn" timestamp without time zone,
    "InterviewCompletedOn" timestamp without time zone,
    "CandidateIdentifiedOn" timestamp without time zone,
    "CandidateDroppedOn" timestamp without time zone,
    "CandidateReintiatedOn" timestamp without time zone,
    "CandidateDropOrReintiateByUserId" integer,
    "CandidateDropOrReintiateByUserComments" text,
    "CandidateFreezedOn" timestamp without time zone,
    "OfferDeclinedOn" timestamp without time zone,
    "OfferRolledOutOn" timestamp without time zone,
    "CandidateOnholdOn" timestamp without time zone,
    "CandidateRejectedOn" timestamp without time zone,
    "OfferAcceptedOn" timestamp without time zone,
    "CandidateJoinedOn" timestamp without time zone,
    "CandidateRescheduledOn" timestamp without time zone,
    "ScreeningStatus" boolean,
    "OriginalHiringRequestId" integer,
    "IsTransferred" boolean,
    "TransferredByUserId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateForms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateForms_DocumentDetails_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES throughline."DocumentDetails" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CandidateForms_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CandidateForms_M_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES throughline."M_Cities" ("Id"),
    CONSTRAINT "FK_CandidateForms_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_CandidateForms_M_MasterData_CandidateStatusId" FOREIGN KEY ("CandidateStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateForms_M_MasterData_IntakeStatusId" FOREIGN KEY ("IntakeStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateForms_M_MasterData_PreviousIntakeStatusId" FOREIGN KEY ("PreviousIntakeStatusId") REFERENCES throughline."M_MasterData" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CandidateForms_M_MasterData_ResourceTypeId" FOREIGN KEY ("ResourceTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateForms_M_States_StateId" FOREIGN KEY ("StateId") REFERENCES throughline."M_States" ("Id"),
    CONSTRAINT "FK_CandidateForms_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id"),
    CONSTRAINT "FK_CandidateForms_Users_ApprovedBy" FOREIGN KEY ("ApprovedBy") REFERENCES throughline."Users" ("UserId") ON DELETE SET NULL,
    CONSTRAINT "FK_CandidateForms_Users_CandidateDropOrReintiateByUserId" FOREIGN KEY ("CandidateDropOrReintiateByUserId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."CandidateFormHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CandidateId" integer,
    "PartnerId" integer,
    "HiringRequestId" integer,
    "IsSingleEntry" boolean NOT NULL,
    "CandidateCode" text,
    "FullName" text,
    "PhoneNumber" text,
    "Email" text,
    "PrimarySkillIds" integer[],
    "SecondarySkillIds" integer[],
    "CountryId" integer,
    "StateId" integer,
    "CityId" integer,
    "Diversity" text,
    "NoticePeriod" integer,
    "RelevantExperience" integer,
    "CurrentlyWorking" text,
    "CurrentOrganisation" text,
    "LastOrganisation" text,
    "LastWorkingDay" timestamp without time zone,
    "ResumeId" integer,
    "EmployeeId" text,
    "ResourceTypeId" integer,
    "PCLifecycleId" text,
    "RequestedMicrosoftAccount" boolean,
    "ConsideredForFutureRequirements" boolean,
    "IsReferred" text,
    "ReferredBy" text,
    "Comments" text,
    "IntakeStatusId" integer,
    "PreviousIntakeStatusId" integer,
    "IsFreezed" boolean,
    "CandidateFreezedReason" text,
    "CandidateStatusId" integer,
    "IsAgreedForTermsConditions" boolean,
    "ApprovedBy" integer,
    "ApprovedDate" timestamp without time zone,
    "IsDuplicate" boolean,
    "IsScreeningCompleted" boolean,
    "ScreeningCompletedOn" timestamp without time zone,
    "InterviewCompletedOn" timestamp without time zone,
    "CandidateIdentifiedOn" timestamp without time zone,
    "CandidateDroppedOn" timestamp without time zone,
    "CandidateReintiatedOn" timestamp without time zone,
    "CandidateDropOrReintiateByUserId" integer,
    "CandidateDropOrReintiateByUserComments" text,
    "CandidateFreezedOn" timestamp without time zone,
    "OfferAcceptedOn" timestamp without time zone,
    "OfferDeclinedOn" timestamp without time zone,
    "OfferRolledOutOn" timestamp without time zone,
    "CandidateOnholdOn" timestamp without time zone,
    "CandidateRejectedOn" timestamp without time zone,
    "CandidateJoinedOn" timestamp without time zone,
    "CandidateRescheduledOn" timestamp without time zone,
    "ScreeningStatus" boolean,
    "ResumeUploadedOn" timestamp without time zone,
    "OriginalHiringRequestId" integer,
    "IsTransferred" boolean,
    "TransferredByUserId" integer,
    "CandidateRateCardId" integer,
    "ReUploadedCandidateOn" timestamp without time zone,
    "CandidateReconsiderationHistoryId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateFormHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_CandidateForms_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES throughline."CandidateForms" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_DocumentDetails_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES throughline."DocumentDetails" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_Hiring_HiringRequestId" FOREIGN KEY ("HiringRequestId") REFERENCES throughline."Hiring" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_M_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES throughline."M_Cities" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_M_MasterData_CandidateStatusId" FOREIGN KEY ("CandidateStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_M_MasterData_IntakeStatusId" FOREIGN KEY ("IntakeStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_M_MasterData_ResourceTypeId" FOREIGN KEY ("ResourceTypeId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_M_States_StateId" FOREIGN KEY ("StateId") REFERENCES throughline."M_States" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id"),
    CONSTRAINT "FK_CandidateFormHistory_Users_ApprovedBy" FOREIGN KEY ("ApprovedBy") REFERENCES throughline."Users" ("UserId") ON DELETE SET NULL
);


CREATE TABLE throughline."CandidatePersonalDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleHiredFor" text,
    "CategoryId" integer,
    "DateOfJoining" timestamp without time zone,
    "CountryId" integer,
    "StateId" integer,
    "CityId" integer,
    "Pincode" text,
    "DomainId" integer,
    "SubDomainId" integer,
    "OnboardingManagerId" integer,
    "PersonalMailId" text,
    "Phone" text,
    "CurrentAddress" text,
    "FinalOnboaridngDate" timestamp without time zone,
    "AadharLast4Digits" text,
    "NameAsPerAadhar" text,
    "JobLocation" text,
    "DOB" text,
    "GenderId" integer,
    "TransportRequirementId" integer,
    "CandidateBGVCompleted" boolean,
    "CandidateId" integer,
    "OnboaridngDateChangeCount" integer,
    "IsRequestException" boolean,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidatePersonalDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_CandidateForms_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES throughline."CandidateForms" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES throughline."M_Cities" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES throughline."M_Countries" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_Domains_DomainId" FOREIGN KEY ("DomainId") REFERENCES throughline."M_Domains" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_MasterData_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_MasterData_GenderId" FOREIGN KEY ("GenderId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_MasterData_TransportRequirementId" FOREIGN KEY ("TransportRequirementId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_States_StateId" FOREIGN KEY ("StateId") REFERENCES throughline."M_States" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_M_SubDomains_SubDomainId" FOREIGN KEY ("SubDomainId") REFERENCES throughline."M_SubDomains" ("Id"),
    CONSTRAINT "FK_CandidatePersonalDetails_Users_OnboardingManagerId" FOREIGN KEY ("OnboardingManagerId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."InterviewSlotAllocation" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InterviewRoundStartDate" timestamp without time zone,
    "InterviewRoundCompleteDate" timestamp without time zone,
    "CandidateId" integer,
    "CurrentRoundId" integer,
    "PartnerId" integer,
    "Panel" integer[],
    "Date" timestamp without time zone,
    "Time" interval,
    "ValidityHours" integer,
    "Duration" integer,
    "HMAdditionalComments" text,
    "CandidateInterviewStatusId" integer,
    "LastStatusUpdated" timestamp without time zone,
    "IsPartnerAccepted" boolean,
    "PartnerInterviewAcceptanceComments" text,
    "RejectionCount" integer,
    "PartenrAcceptedOn" timestamp without time zone,
    "IsInterviewCompleted" boolean,
    "ResheduledOrDropped" integer,
    "ResheduleIntiatedBy" integer,
    "PartnerInterviewCompletedComments" text,
    "PartnerInterviewConfirmedOn" timestamp without time zone,
    "RescheduleCount" integer,
    "Feedback" text,
    "PanelFeedbackGivenOn" timestamp without time zone,
    "FeedbackGivenByUserId" integer,
    "IsResheduled" boolean,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_InterviewSlotAllocation" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterviewSlotAllocation_CandidateForms_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES throughline."CandidateForms" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_InterviewSlotAllocation_InterviewRounds_CurrentRoundId" FOREIGN KEY ("CurrentRoundId") REFERENCES throughline."InterviewRounds" ("Id"),
    CONSTRAINT "FK_InterviewSlotAllocation_M_MasterData_CandidateInterviewStat~" FOREIGN KEY ("CandidateInterviewStatusId") REFERENCES throughline."M_MasterData" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_InterviewSlotAllocation_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES throughline."Partners" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_InterviewSlotAllocation_Users_FeedbackGivenByUserId" FOREIGN KEY ("FeedbackGivenByUserId") REFERENCES throughline."Users" ("UserId") ON DELETE SET NULL
);


CREATE TABLE throughline."ProfileTracker" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsEmployeeIdGenerated" boolean,
    "EmployeeNameAsPerId" text,
    "EmployeeId" integer,
    "HPEEmailId" text,
    "ProfileCreatedOn" timestamp without time zone,
    "SmartProfileId" text,
    "ProfileApprovalDate" timestamp without time zone,
    "LHCCCode" text,
    "CostCenterId" integer,
    "CostCenterName" text,
    "CandidatePersonalDetailsId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_ProfileTracker" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProfileTracker_CandidatePersonalDetails_CandidatePersonalDe~" FOREIGN KEY ("CandidatePersonalDetailsId") REFERENCES throughline."CandidatePersonalDetails" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProfileTracker_M_MasterData_CostCenterId" FOREIGN KEY ("CostCenterId") REFERENCES throughline."M_MasterData" ("Id")
);


CREATE TABLE throughline."TrainingDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsMovedToManager" boolean,
    "SessionTakenByManagerId" integer,
    "TrainingModuleIds" integer[],
    "ReleaseToOperationsDate" timestamp without time zone,
    "IsTrainingCompleted" boolean,
    "TrainingSharedOn" timestamp without time zone,
    "TrainingCompleted" timestamp without time zone,
    "IsOrientationCompleted" boolean,
    "OrientationDate" timestamp without time zone,
    "OrientationCompletionDate" timestamp without time zone,
    "RescheduleOrientationDate" timestamp without time zone,
    "OrientationSharedOn" timestamp without time zone,
    "OrientationStatusId" integer,
    "ReasonForReschedule" text,
    "ResumeUploadId" integer,
    "RCMSUploadStatusId" integer,
    "CandidatePersonalDetailsId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_TrainingDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TrainingDetails_CandidatePersonalDetails_CandidatePersonalD~" FOREIGN KEY ("CandidatePersonalDetailsId") REFERENCES throughline."CandidatePersonalDetails" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TrainingDetails_DocumentDetails_ResumeUploadId" FOREIGN KEY ("ResumeUploadId") REFERENCES throughline."DocumentDetails" ("Id"),
    CONSTRAINT "FK_TrainingDetails_M_MasterData_OrientationStatusId" FOREIGN KEY ("OrientationStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_TrainingDetails_M_MasterData_RCMSUploadStatusId" FOREIGN KEY ("RCMSUploadStatusId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_TrainingDetails_Users_SessionTakenByManagerId" FOREIGN KEY ("SessionTakenByManagerId") REFERENCES throughline."Users" ("UserId")
);


CREATE TABLE throughline."CandidateInterviewFeedBack" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InterviewSlotId" integer,
    "CandidateId" integer,
    "FeedbackCategoryId" integer,
    "CriteriaOptionId" integer,
    "Rating" integer,
    "Comments" text,
    "InterviewSlotAllocationHistoryId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_CandidateInterviewFeedBack" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateInterviewFeedBack_InterviewSlotAllocationHistory_I~" FOREIGN KEY ("InterviewSlotAllocationHistoryId") REFERENCES throughline."InterviewSlotAllocationHistory" ("Id"),
    CONSTRAINT "FK_CandidateInterviewFeedBack_InterviewSlotAllocation_Intervie~" FOREIGN KEY ("InterviewSlotId") REFERENCES throughline."InterviewSlotAllocation" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CandidateInterviewFeedBack_M_MasterData_CriteriaOptionId" FOREIGN KEY ("CriteriaOptionId") REFERENCES throughline."M_MasterData" ("Id"),
    CONSTRAINT "FK_CandidateInterviewFeedBack_M_MasterData_FeedbackCategoryId" FOREIGN KEY ("FeedbackCategoryId") REFERENCES throughline."M_MasterData" ("Id")
);


CREATE TABLE throughline."InterviewActionLog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InterviewSlotId" integer NOT NULL,
    "ActionType" integer NOT NULL,
    "ActionTime" timestamp without time zone NOT NULL,
    "Comments" text,
    "PerformedByUserId" integer,
    "IsActive" boolean,
    "CreatedBy" integer,
    "CreatedAt" timestamp without time zone,
    "UpdatedBy" integer,
    "UpdatedAt" timestamp without time zone,
    CONSTRAINT "PK_InterviewActionLog" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterviewActionLog_InterviewSlotAllocation_InterviewSlotId" FOREIGN KEY ("InterviewSlotId") REFERENCES throughline."InterviewSlotAllocation" ("Id") ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_AssetDetails_CandidatePersonalDetailsId" ON throughline."AssetDetails" ("CandidatePersonalDetailsId");


CREATE INDEX "IX_AssetDetails_ComplianceFollowedId" ON throughline."AssetDetails" ("ComplianceFollowedId");


CREATE INDEX "IX_AssetDetails_DelayCategoryId" ON throughline."AssetDetails" ("DelayCategoryId");


CREATE INDEX "IX_AssetDetails_ITAssetStatusID" ON throughline."AssetDetails" ("ITAssetStatusID");


CREATE INDEX "IX_AssetDetails_ModeOfPcShipmentId" ON throughline."AssetDetails" ("ModeOfPcShipmentId");


CREATE INDEX "IX_Calibrations_DocumentsId" ON throughline."Calibrations" ("DocumentsId");


CREATE INDEX "IX_CandidateBgvDetails_CDAAvailabilityDocId" ON throughline."CandidateBgvDetails" ("CDAAvailabilityDocId");


CREATE INDEX "IX_CandidateBgvDetails_NDAAvailabilityDocId" ON throughline."CandidateBgvDetails" ("NDAAvailabilityDocId");


CREATE INDEX "IX_CandidateBgvDetails_PGUId" ON throughline."CandidateBgvDetails" ("PGUId");


CREATE INDEX "IX_CandidateBgvDetails_VendorId" ON throughline."CandidateBgvDetails" ("VendorId");


CREATE INDEX "IX_CandidateBin_ApprovedOrDeclinedByUserId" ON throughline."CandidateBin" ("ApprovedOrDeclinedByUserId");


CREATE INDEX "IX_CandidateBin_CityId" ON throughline."CandidateBin" ("CityId");


CREATE INDEX "IX_CandidateBin_CountryId" ON throughline."CandidateBin" ("CountryId");


CREATE INDEX "IX_CandidateBin_HiringRequestId" ON throughline."CandidateBin" ("HiringRequestId");


CREATE INDEX "IX_CandidateBin_IntakeStatusId" ON throughline."CandidateBin" ("IntakeStatusId");


CREATE INDEX "IX_CandidateBin_PartnerId" ON throughline."CandidateBin" ("PartnerId");


CREATE INDEX "IX_CandidateBin_ResourceTypeId" ON throughline."CandidateBin" ("ResourceTypeId");


CREATE INDEX "IX_CandidateBin_ResumeId" ON throughline."CandidateBin" ("ResumeId");


CREATE INDEX "IX_CandidateBin_StateId" ON throughline."CandidateBin" ("StateId");


CREATE INDEX "IX_CandidateBinHistory_ApprovedOrDeclinedByUserId" ON throughline."CandidateBinHistory" ("ApprovedOrDeclinedByUserId");


CREATE INDEX "IX_CandidateBinHistory_CityId" ON throughline."CandidateBinHistory" ("CityId");


CREATE INDEX "IX_CandidateBinHistory_CountryId" ON throughline."CandidateBinHistory" ("CountryId");


CREATE INDEX "IX_CandidateBinHistory_HiringRequestId" ON throughline."CandidateBinHistory" ("HiringRequestId");


CREATE INDEX "IX_CandidateBinHistory_IntakeStatusId" ON throughline."CandidateBinHistory" ("IntakeStatusId");


CREATE INDEX "IX_CandidateBinHistory_PartnerId" ON throughline."CandidateBinHistory" ("PartnerId");


CREATE INDEX "IX_CandidateBinHistory_ResourceTypeId" ON throughline."CandidateBinHistory" ("ResourceTypeId");


CREATE INDEX "IX_CandidateBinHistory_ResumeId" ON throughline."CandidateBinHistory" ("ResumeId");


CREATE INDEX "IX_CandidateBinHistory_StateId" ON throughline."CandidateBinHistory" ("StateId");


CREATE INDEX "IX_CandidateFormHistory_ApprovedBy" ON throughline."CandidateFormHistory" ("ApprovedBy");


CREATE INDEX "IX_CandidateFormHistory_CandidateId" ON throughline."CandidateFormHistory" ("CandidateId");


CREATE INDEX "IX_CandidateFormHistory_CandidateStatusId" ON throughline."CandidateFormHistory" ("CandidateStatusId");


CREATE INDEX "IX_CandidateFormHistory_CityId" ON throughline."CandidateFormHistory" ("CityId");


CREATE INDEX "IX_CandidateFormHistory_CountryId" ON throughline."CandidateFormHistory" ("CountryId");


CREATE INDEX "IX_CandidateFormHistory_HiringRequestId" ON throughline."CandidateFormHistory" ("HiringRequestId");


CREATE INDEX "IX_CandidateFormHistory_IntakeStatusId" ON throughline."CandidateFormHistory" ("IntakeStatusId");


CREATE INDEX "IX_CandidateFormHistory_PartnerId" ON throughline."CandidateFormHistory" ("PartnerId");


CREATE INDEX "IX_CandidateFormHistory_ResourceTypeId" ON throughline."CandidateFormHistory" ("ResourceTypeId");


CREATE INDEX "IX_CandidateFormHistory_ResumeId" ON throughline."CandidateFormHistory" ("ResumeId");


CREATE INDEX "IX_CandidateFormHistory_StateId" ON throughline."CandidateFormHistory" ("StateId");


CREATE INDEX "IX_CandidateForms_ApprovedBy" ON throughline."CandidateForms" ("ApprovedBy");


CREATE INDEX "IX_CandidateForms_CandidateDropOrReintiateByUserId" ON throughline."CandidateForms" ("CandidateDropOrReintiateByUserId");


CREATE INDEX "IX_CandidateForms_CandidateStatusId" ON throughline."CandidateForms" ("CandidateStatusId");


CREATE INDEX "IX_CandidateForms_CityId" ON throughline."CandidateForms" ("CityId");


CREATE INDEX "IX_CandidateForms_CountryId" ON throughline."CandidateForms" ("CountryId");


CREATE INDEX "IX_CandidateForms_HiringRequestId" ON throughline."CandidateForms" ("HiringRequestId");


CREATE INDEX "IX_CandidateForms_IntakeStatusId" ON throughline."CandidateForms" ("IntakeStatusId");


CREATE INDEX "IX_CandidateForms_PartnerId" ON throughline."CandidateForms" ("PartnerId");


CREATE INDEX "IX_CandidateForms_PreviousIntakeStatusId" ON throughline."CandidateForms" ("PreviousIntakeStatusId");


CREATE INDEX "IX_CandidateForms_ResourceTypeId" ON throughline."CandidateForms" ("ResourceTypeId");


CREATE INDEX "IX_CandidateForms_ResumeId" ON throughline."CandidateForms" ("ResumeId");


CREATE INDEX "IX_CandidateForms_StateId" ON throughline."CandidateForms" ("StateId");


CREATE INDEX "IX_CandidateInterviewFeedBack_CriteriaOptionId" ON throughline."CandidateInterviewFeedBack" ("CriteriaOptionId");


CREATE INDEX "IX_CandidateInterviewFeedBack_FeedbackCategoryId" ON throughline."CandidateInterviewFeedBack" ("FeedbackCategoryId");


CREATE INDEX "IX_CandidateInterviewFeedBack_InterviewSlotAllocationHistoryId" ON throughline."CandidateInterviewFeedBack" ("InterviewSlotAllocationHistoryId");


CREATE INDEX "IX_CandidateInterviewFeedBack_InterviewSlotId" ON throughline."CandidateInterviewFeedBack" ("InterviewSlotId");


CREATE UNIQUE INDEX "IX_CandidatePersonalDetails_CandidateId" ON throughline."CandidatePersonalDetails" ("CandidateId");


CREATE INDEX "IX_CandidatePersonalDetails_CategoryId" ON throughline."CandidatePersonalDetails" ("CategoryId");


CREATE INDEX "IX_CandidatePersonalDetails_CityId" ON throughline."CandidatePersonalDetails" ("CityId");


CREATE INDEX "IX_CandidatePersonalDetails_CountryId" ON throughline."CandidatePersonalDetails" ("CountryId");


CREATE INDEX "IX_CandidatePersonalDetails_DomainId" ON throughline."CandidatePersonalDetails" ("DomainId");


CREATE INDEX "IX_CandidatePersonalDetails_GenderId" ON throughline."CandidatePersonalDetails" ("GenderId");


CREATE INDEX "IX_CandidatePersonalDetails_OnboardingManagerId" ON throughline."CandidatePersonalDetails" ("OnboardingManagerId");


CREATE INDEX "IX_CandidatePersonalDetails_StateId" ON throughline."CandidatePersonalDetails" ("StateId");


CREATE INDEX "IX_CandidatePersonalDetails_SubDomainId" ON throughline."CandidatePersonalDetails" ("SubDomainId");


CREATE INDEX "IX_CandidatePersonalDetails_TransportRequirementId" ON throughline."CandidatePersonalDetails" ("TransportRequirementId");


CREATE INDEX "IX_CandidateRateCard_CandidateCategotyId" ON throughline."CandidateRateCard" ("CandidateCategotyId");


CREATE UNIQUE INDEX "IX_CandidateRateCard_CandidateId" ON throughline."CandidateRateCard" ("CandidateId");


CREATE INDEX "IX_CandidateRateCard_CategoryId" ON throughline."CandidateRateCard" ("CategoryId");


CREATE INDEX "IX_CandidateReconsiderationHistory_ReconsiderReasonId" ON throughline."CandidateReconsiderationHistory" ("ReconsiderReasonId");


CREATE INDEX "IX_ContactMatrices_ContactMatrixTypeId" ON throughline."ContactMatrices" ("ContactMatrixTypeId");


CREATE INDEX "IX_ContactMatrices_CountryId" ON throughline."ContactMatrices" ("CountryId");


CREATE INDEX "IX_ContactMatrices_PartnerId" ON throughline."ContactMatrices" ("PartnerId");


CREATE INDEX "IX_ContactMatrices_StatusId" ON throughline."ContactMatrices" ("StatusId");


CREATE INDEX "IX_DocumentDetails_AdditionalDocId" ON throughline."DocumentDetails" ("AdditionalDocId");


CREATE INDEX "IX_DocumentDetails_PartnerEmpanelId" ON throughline."DocumentDetails" ("PartnerEmpanelId");


CREATE INDEX "IX_DocumentDetails_PartnerId" ON throughline."DocumentDetails" ("PartnerId");


CREATE INDEX "IX_DocumentDetails_UploadBGVDocId" ON throughline."DocumentDetails" ("UploadBGVDocId");


CREATE INDEX "IX_EngagementHistory_BusinessUnitId" ON throughline."EngagementHistory" ("BusinessUnitId");


CREATE INDEX "IX_EngagementHistory_CreatedBy" ON throughline."EngagementHistory" ("CreatedBy");


CREATE INDEX "IX_EngagementHistory_EngagementStatusId" ON throughline."EngagementHistory" ("EngagementStatusId");


CREATE INDEX "IX_EngagementHistory_EngagementTypeId" ON throughline."EngagementHistory" ("EngagementTypeId");


CREATE INDEX "IX_EngagementHistory_EvaluationStatusId" ON throughline."EngagementHistory" ("EvaluationStatusId");


CREATE INDEX "IX_EngagementHistory_PartnerId" ON throughline."EngagementHistory" ("PartnerId");


CREATE INDEX "IX_EngagementHistory_RejectionReasonTypeId" ON throughline."EngagementHistory" ("RejectionReasonTypeId");


CREATE INDEX "IX_Engagements_BusinessId" ON throughline."Engagements" ("BusinessId");


CREATE INDEX "IX_Engagements_EngagementStatusId" ON throughline."Engagements" ("EngagementStatusId");


CREATE INDEX "IX_Engagements_EngagementTypeId" ON throughline."Engagements" ("EngagementTypeId");


CREATE INDEX "IX_Engagements_EvaluationStatusId" ON throughline."Engagements" ("EvaluationStatusId");


CREATE INDEX "IX_Engagements_PartnerId" ON throughline."Engagements" ("PartnerId");


CREATE INDEX "IX_Engagements_RejectionReasonTypeId" ON throughline."Engagements" ("RejectionReasonTypeId");


CREATE INDEX "IX_EscalationMatrices_ContactTypeId" ON throughline."EscalationMatrices" ("ContactTypeId");


CREATE INDEX "IX_EscalationMatrices_CountryId" ON throughline."EscalationMatrices" ("CountryId");


CREATE INDEX "IX_EscalationMatrices_PartnerId" ON throughline."EscalationMatrices" ("PartnerId");


CREATE INDEX "IX_EscalationMatrices_StatusId" ON throughline."EscalationMatrices" ("StatusId");


CREATE INDEX "IX_FeedbackCritriaOptions_CriteriaOptionId" ON throughline."FeedbackCritriaOptions" ("CriteriaOptionId");


CREATE INDEX "IX_FeedbackCritriaOptions_InterviewRoundId" ON throughline."FeedbackCritriaOptions" ("InterviewRoundId");


CREATE INDEX "IX_FeedbackDetail_FeedbackId" ON throughline."FeedbackDetail" ("FeedbackId");


CREATE INDEX "IX_Forms_ModuleId" ON throughline."Forms" ("ModuleId");


CREATE INDEX "IX_Hiring_ApprovalStatusId" ON throughline."Hiring" ("ApprovalStatusId");


CREATE INDEX "IX_Hiring_BETApproverId" ON throughline."Hiring" ("BETApproverId");


CREATE INDEX "IX_Hiring_BusinessId" ON throughline."Hiring" ("BusinessId");


CREATE INDEX "IX_Hiring_DomainId" ON throughline."Hiring" ("DomainId");


CREATE INDEX "IX_Hiring_EngagementTypeId" ON throughline."Hiring" ("EngagementTypeId");


CREATE INDEX "IX_Hiring_HiringMangerId" ON throughline."Hiring" ("HiringMangerId");


CREATE INDEX "IX_Hiring_HiringStatusId" ON throughline."Hiring" ("HiringStatusId");


CREATE INDEX "IX_Hiring_HiringTypeId" ON throughline."Hiring" ("HiringTypeId");


CREATE INDEX "IX_Hiring_OnholdRaisedBy" ON throughline."Hiring" ("OnholdRaisedBy");


CREATE INDEX "IX_Hiring_OnholdReasonId" ON throughline."Hiring" ("OnholdReasonId");


CREATE INDEX "IX_Hiring_OnholdRequestedBy" ON throughline."Hiring" ("OnholdRequestedBy");


CREATE INDEX "IX_Hiring_OnholdReviewedByUserId" ON throughline."Hiring" ("OnholdReviewedByUserId");


CREATE INDEX "IX_Hiring_OnHoldReviewStatusId" ON throughline."Hiring" ("OnHoldReviewStatusId");


CREATE INDEX "IX_Hiring_PreviousHiringStatusId" ON throughline."Hiring" ("PreviousHiringStatusId");


CREATE INDEX "IX_Hiring_RecordTypeId" ON throughline."Hiring" ("RecordTypeId");


CREATE INDEX "IX_Hiring_RequestApproverId" ON throughline."Hiring" ("RequestApproverId");


CREATE INDEX "IX_Hiring_RequestorId" ON throughline."Hiring" ("RequestorId");


CREATE INDEX "IX_Hiring_RmOwnerId" ON throughline."Hiring" ("RmOwnerId");


CREATE INDEX "IX_HiringReqPartner_PartnerCategoryId" ON throughline."HiringReqPartner" ("PartnerCategoryId");


CREATE INDEX "IX_InterviewActionLog_InterviewSlotId" ON throughline."InterviewActionLog" ("InterviewSlotId");


CREATE INDEX "IX_InterviewRounds_HiringRequestId" ON throughline."InterviewRounds" ("HiringRequestId");


CREATE INDEX "IX_InterviewRounds_ModeOfInterview" ON throughline."InterviewRounds" ("ModeOfInterview");


CREATE INDEX "IX_InterviewRounds_RoundNameId" ON throughline."InterviewRounds" ("RoundNameId");


CREATE INDEX "IX_InterviewSlotAllocation_CandidateId" ON throughline."InterviewSlotAllocation" ("CandidateId");


CREATE INDEX "IX_InterviewSlotAllocation_CandidateInterviewStatusId" ON throughline."InterviewSlotAllocation" ("CandidateInterviewStatusId");


CREATE INDEX "IX_InterviewSlotAllocation_CurrentRoundId" ON throughline."InterviewSlotAllocation" ("CurrentRoundId");


CREATE INDEX "IX_InterviewSlotAllocation_FeedbackGivenByUserId" ON throughline."InterviewSlotAllocation" ("FeedbackGivenByUserId");


CREATE INDEX "IX_InterviewSlotAllocation_PartnerId" ON throughline."InterviewSlotAllocation" ("PartnerId");


CREATE INDEX "IX_InterviewSlotAllocationHistory_CandidateInterviewStatusId" ON throughline."InterviewSlotAllocationHistory" ("CandidateInterviewStatusId");


CREATE INDEX "IX_InterviewSlotAllocationHistory_CurrentRoundId" ON throughline."InterviewSlotAllocationHistory" ("CurrentRoundId");


CREATE INDEX "IX_InterviewSlotAllocationHistory_HiringRequestId" ON throughline."InterviewSlotAllocationHistory" ("HiringRequestId");


CREATE INDEX "IX_InterviewSlotAllocationHistory_PartnerId" ON throughline."InterviewSlotAllocationHistory" ("PartnerId");


CREATE INDEX "IX_JobDetails_CountryId" ON throughline."JobDetails" ("CountryId");


CREATE INDEX "IX_JobDetails_HiringActivityId" ON throughline."JobDetails" ("HiringActivityId");


CREATE UNIQUE INDEX "IX_JobDetails_HiringRequestId" ON throughline."JobDetails" ("HiringRequestId");


CREATE INDEX "IX_JobDetails_JobLevelId" ON throughline."JobDetails" ("JobLevelId");


CREATE INDEX "IX_JobDetails_JobPriorityId" ON throughline."JobDetails" ("JobPriorityId");


CREATE INDEX "IX_JobDetails_ResourceTypeId" ON throughline."JobDetails" ("ResourceTypeId");


CREATE INDEX "IX_JobDetails_SubDomainId" ON throughline."JobDetails" ("SubDomainId");


CREATE INDEX "IX_JoiningRescheduleHistory_Modifiedby" ON throughline."JoiningRescheduleHistory" ("Modifiedby");


CREATE UNIQUE INDEX "IX_M_Cities_Name" ON throughline."M_Cities" ("Name");


CREATE INDEX "IX_M_Cities_StateId" ON throughline."M_Cities" ("StateId");


CREATE UNIQUE INDEX "IX_M_Countries_Name" ON throughline."M_Countries" ("Name");


CREATE INDEX "IX_M_Domains_DomainManagerId" ON throughline."M_Domains" ("DomainManagerId");


CREATE UNIQUE INDEX "IX_M_Domains_Name" ON throughline."M_Domains" ("Name");


CREATE INDEX "IX_M_States_CountryId" ON throughline."M_States" ("CountryId");


CREATE UNIQUE INDEX "IX_M_States_Name" ON throughline."M_States" ("Name");


CREATE INDEX "IX_M_SubDomains_DomainId" ON throughline."M_SubDomains" ("DomainId");


CREATE UNIQUE INDEX "IX_M_SubDomains_Name" ON throughline."M_SubDomains" ("Name");


CREATE UNIQUE INDEX "IX_M_SubDomains_Name_DomainId" ON throughline."M_SubDomains" ("Name", "DomainId");


CREATE INDEX "IX_M_SubDomains_SubDomainManagerId" ON throughline."M_SubDomains" ("SubDomainManagerId");


CREATE INDEX "IX_OnholdHiringRequest_HiringRequestId" ON throughline."OnholdHiringRequest" ("HiringRequestId");


CREATE INDEX "IX_OnholdHiringRequest_OnholdCategoryId" ON throughline."OnholdHiringRequest" ("OnholdCategoryId");


CREATE INDEX "IX_OnholdHiringRequest_OnholdRaisedByUserId" ON throughline."OnholdHiringRequest" ("OnholdRaisedByUserId");


CREATE INDEX "IX_OnholdHiringRequest_OnholdReasonId" ON throughline."OnholdHiringRequest" ("OnholdReasonId");


CREATE INDEX "IX_OnholdHiringRequest_OnholdRequestedByRoleId" ON throughline."OnholdHiringRequest" ("OnholdRequestedByRoleId");


CREATE INDEX "IX_OnholdHiringRequest_OnHoldReviewedByUserId" ON throughline."OnholdHiringRequest" ("OnHoldReviewedByUserId");


CREATE INDEX "IX_OnholdHiringRequest_ReviewStatusId" ON throughline."OnholdHiringRequest" ("ReviewStatusId");


CREATE INDEX "IX_PartnerApprovalHistory_PartnerId" ON throughline."PartnerApprovalHistory" ("PartnerId");


CREATE UNIQUE INDEX "IX_PartnerCategories_HiringRequestId" ON throughline."PartnerCategories" ("HiringRequestId");


CREATE INDEX "IX_PartnerEmpanel_AgreementTypeId" ON throughline."PartnerEmpanel" ("AgreementTypeId");


CREATE UNIQUE INDEX "IX_PartnerEmpanel_PartnerId" ON throughline."PartnerEmpanel" ("PartnerId");


CREATE INDEX "IX_PartnerEmpanel_RejectionReasonId" ON throughline."PartnerEmpanel" ("RejectionReasonId");


CREATE INDEX "IX_Partners_ApprovedBy" ON throughline."Partners" ("ApprovedBy");


CREATE INDEX "IX_Partners_CityId" ON throughline."Partners" ("CityId");


CREATE INDEX "IX_Partners_CountryId" ON throughline."Partners" ("CountryId");


CREATE INDEX "IX_Partners_LastReinitiatedBy" ON throughline."Partners" ("LastReinitiatedBy");


CREATE INDEX "IX_Partners_PartnerCategoryId" ON throughline."Partners" ("PartnerCategoryId");


CREATE UNIQUE INDEX "IX_Partners_PartnerName" ON throughline."Partners" ("PartnerName");


CREATE INDEX "IX_Partners_PartnerStatusId" ON throughline."Partners" ("PartnerStatusId");


CREATE INDEX "IX_Partners_PartnerTireId" ON throughline."Partners" ("PartnerTireId");


CREATE INDEX "IX_Partners_ServicingCountryId" ON throughline."Partners" ("ServicingCountryId");


CREATE INDEX "IX_Partners_StateId" ON throughline."Partners" ("StateId");


CREATE INDEX "IX_POCRS_POId" ON throughline."POCRS" ("POId");


CREATE UNIQUE INDEX "IX_ProfileTracker_CandidatePersonalDetailsId" ON throughline."ProfileTracker" ("CandidatePersonalDetailsId");


CREATE INDEX "IX_ProfileTracker_CostCenterId" ON throughline."ProfileTracker" ("CostCenterId");


CREATE INDEX "IX_RCMSDetails_HiringManagerId" ON throughline."RCMSDetails" ("HiringManagerId");


CREATE INDEX "IX_RoleFormAccess_FormId" ON throughline."RoleFormAccess" ("FormId");


CREATE INDEX "IX_SOWCRS_SOWId" ON throughline."SOWCRS" ("SOWId");


CREATE INDEX "IX_SOWDetailHistory_PartnerId" ON throughline."SOWDetailHistory" ("PartnerId");


CREATE INDEX "IX_SOWDetails_PartnerId" ON throughline."SOWDetails" ("PartnerId");


CREATE UNIQUE INDEX "IX_SOWDetails_SOWNumber" ON throughline."SOWDetails" ("SOWNumber");


CREATE UNIQUE INDEX "IX_SOWPODetail_PONumber" ON throughline."SOWPODetail" ("PONumber");


CREATE INDEX "IX_SOWPODetail_SowId" ON throughline."SOWPODetail" ("SowId");


CREATE UNIQUE INDEX "IX_TrainingDetails_CandidatePersonalDetailsId" ON throughline."TrainingDetails" ("CandidatePersonalDetailsId");


CREATE INDEX "IX_TrainingDetails_OrientationStatusId" ON throughline."TrainingDetails" ("OrientationStatusId");


CREATE INDEX "IX_TrainingDetails_RCMSUploadStatusId" ON throughline."TrainingDetails" ("RCMSUploadStatusId");


CREATE INDEX "IX_TrainingDetails_ResumeUploadId" ON throughline."TrainingDetails" ("ResumeUploadId");


CREATE INDEX "IX_TrainingDetails_SessionTakenByManagerId" ON throughline."TrainingDetails" ("SessionTakenByManagerId");


CREATE INDEX "IX_UserRolesMapping_PartnerId" ON throughline."UserRolesMapping" ("PartnerId");


CREATE INDEX "IX_UserRolesMapping_RoleId" ON throughline."UserRolesMapping" ("RoleId");


ALTER TABLE throughline."AssetDetails" ADD CONSTRAINT "FK_AssetDetails_CandidatePersonalDetails_CandidatePersonalDeta~" FOREIGN KEY ("CandidatePersonalDetailsId") REFERENCES throughline."CandidatePersonalDetails" ("Id") ON DELETE CASCADE;


ALTER TABLE throughline."Calibrations" ADD CONSTRAINT "FK_Calibrations_DocumentDetails_DocumentsId" FOREIGN KEY ("DocumentsId") REFERENCES throughline."DocumentDetails" ("Id");


ALTER TABLE throughline."CandidateBgvDetails" ADD CONSTRAINT "FK_CandidateBgvDetails_DocumentDetails_CDAAvailabilityDocId" FOREIGN KEY ("CDAAvailabilityDocId") REFERENCES throughline."DocumentDetails" ("Id");


ALTER TABLE throughline."CandidateBgvDetails" ADD CONSTRAINT "FK_CandidateBgvDetails_DocumentDetails_NDAAvailabilityDocId" FOREIGN KEY ("NDAAvailabilityDocId") REFERENCES throughline."DocumentDetails" ("Id");


